version: '3.5'
services:
  # hello:
  #   image: nginx
  #   networks:
  #     - gwen-net
  selenoid:
    image: aerokube/selenoid:latest-release
    networks:
      - gwen-net
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/browsers:/etc/selenoid/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-container-network", "gwen-net"]
  chrome:
    image: selenoid/chrome:latest
    networks:
      - gwen-net
networks:
  gwen-net:
    name: gwen-net
