version: '3.5'
services:
  hello:
    image: nginx
    networks:
      - gwen-net
  hello2:
    image: nginx
    networks:
      - gwen-net
  # chrome:
  #   image: selenoid/chrome:latest
  #   networks:
  #     - gwen-net
networks:
  gwen-net:
    name: gwen-net
